### ISSUE TITLE
[417719] FTBFS with GCC 4.3: missing #includes

### ISSUE THREAD

**Issue by epakai** [epakai/synergy-debian#16]

**Comment by epakai** [comment]
BTS_msg_id: <20070404121546.GH9832@deprecation.cyrius.com>
BTS author: Martin Michlmayr <tbm@cyrius.com>

Package: synergy
Version: 1.3.1-2
Usertags: ftbfs-gcc-4.3
Tags: patch

Your package fails to build with GCC 4.3.  Version 4.3 has not been
released yet but I'm building with a snapshot in order to find errors
and give people an advance warning.  In GCC 4.3, the C++ header
dependencies have been cleaned up.  The advantage of this is that
programs will compile faster.  The downside is that you actually
need to directly #include everything you use (but you really should
do this anyway, otherwise your program won't work with any compiler
other than GCC).  Some background of this can be found at
http://gcc.gnu.org/PR28080

You can reproduce this problem with gcc-snapshot (20070326-1 or higher)
from unstable. (Currently not available for i386, but for amd64, powerpc
and ia64.  I hope to have i386 binaries in the archive in ~3 weeks.)

> Automatic build of synergy_1.3.1-2 on coconut0 by sbuild/ia64 0.49
...
> 	FOO=5 depmode=gcc3 /bin/sh ../../config/depcomp \
> 	ia64-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I. -I../.. -I../../lib/common     -g -O2 -g -Wall -Wno-unknown-pragmas -Werror   -DSYSAPI_UNIX=1 -DWINAPI_XWINDOWS=1 -pthread  -c -o CArchDaemonUnix.o `test -f 'CArchDaemonUnix.cpp' || echo './'`CArchDaemonUnix.cpp
> CArchDaemonUnix.cpp: In member function 'virtual int CArchDaemonUnix::daemonize(const char*, int (*)(int, const char**))':
> CArchDaemonUnix.cpp:53: error: 'exit' was not declared in this scope
> make[4]: *** [CArchDaemonUnix.o] Error 1

--- lib/arch/CArchDaemonUnix.cpp~	2007-04-04 11:49:58.000000000 +0000
+++ lib/arch/CArchDaemonUnix.cpp	2007-04-04 11:50:33.000000000 +0000
@@ -18,6 +18,7 @@
 #include <sys/types.h>
 #include <sys/stat.h>
 #include <fcntl.h>
+#include <cstdlib>
 #include <errno.h>
 
 //
--- lib/arch/CMultibyte.cpp~	2007-04-04 11:50:52.000000000 +0000
+++ lib/arch/CMultibyte.cpp	2007-04-04 11:51:17.000000000 +0000
@@ -17,6 +17,7 @@
 
 #include "common.h"
 #include "CArch.h"
+#include <cstdlib>
 #include <limits.h>
 #include <string.h>
 #if HAVE_LOCALE_H
--- lib/client/CClient.cpp~	2007-04-04 12:03:07.000000000 +0000
+++ lib/client/CClient.cpp	2007-04-04 12:03:14.000000000 +0000
@@ -26,6 +26,7 @@
 #include "CLog.h"
 #include "IEventQueue.h"
 #include "TMethodEventJob.h"
+#include <cstdlib>
 
 //
 // CClient
--- lib/net/CTCPSocket.cpp~	2007-04-04 11:53:39.000000000 +0000
+++ lib/net/CTCPSocket.cpp	2007-04-04 11:53:58.000000000 +0000
@@ -23,6 +23,7 @@
 #include "IEventJob.h"
 #include "CArch.h"
 #include "XArch.h"
+#include <cstdlib>
 #include <string.h>
 
 //
--- lib/platform/CXWindowsScreen.cpp~	2007-04-04 12:02:14.000000000 +0000
+++ lib/platform/CXWindowsScreen.cpp	2007-04-04 12:02:25.000000000 +0000
@@ -51,6 +51,7 @@
 #	endif
 #endif
 #include "CArch.h"
+#include <cstdlib>
 
 
 //
--- lib/server/CServer.cpp~	2007-04-04 12:05:20.000000000 +0000
+++ lib/server/CServer.cpp	2007-04-04 12:05:26.000000000 +0000
@@ -29,6 +29,7 @@
 #include "TMethodEventJob.h"
 #include "CArch.h"
 #include <string.h>
+#include <cstdlib>
 
 //
 // CServer
--- lib/synergy/IKeyState.cpp~	2007-04-04 12:00:26.000000000 +0000
+++ lib/synergy/IKeyState.cpp	2007-04-04 12:00:41.000000000 +0000
@@ -13,6 +13,7 @@
  */
 
 #include "IKeyState.h"
+#include <cstdlib>
 #include <string.h>
 
 //
--- lib/synergy/IPrimaryScreen.cpp~	2007-04-04 12:00:56.000000000 +0000
+++ lib/synergy/IPrimaryScreen.cpp	2007-04-04 12:01:02.000000000 +0000
@@ -13,6 +13,7 @@
  */
 
 #include "IPrimaryScreen.h"
+#include <cstdlib>
 
 //
 // IPrimaryScreen


Unfortunately now we fail with:

                 from CClientTaskBarReceiver.cpp:15:
../../lib/arch/IArchTaskBarReceiver.h:77: error: type qualifiers ignored on function return type
In file included from CClientTaskBarReceiver.cpp:15:
CClientTaskBarReceiver.h:46: error: type qualifiers ignored on function return type

-- 
Martin Michlmayr
http://www.cyrius.com/

**Comment by epakai** [comment]
BTS_msg_id: <18011.61939.15455.539718@gargle.gargle.HOWL>
BTS author: Matthias Klose <doko@cs.tu-berlin.de>

severity 413413 important
severity 413416 important
severity 413417 important
severity 413419 important
severity 413420 important
severity 413427 important
severity 413432 important
severity 413485 important
severity 413487 important
severity 416852 important
severity 416859 important
severity 417062 important
severity 417069 important
severity 417075 important
severity 417078 important
severity 417081 important
severity 417082 important
severity 417083 important
severity 417088 important
severity 417090 important
severity 417092 important
severity 417099 important
severity 417102 important
severity 417104 important
severity 417108 important
severity 417110 important
severity 417111 important
severity 417112 important
severity 417114 important
severity 417116 important
severity 417117 important
severity 417120 important
severity 417122 important
severity 417124 important
severity 417126 important
severity 417127 important
severity 417128 important
severity 417129 important
severity 417131 important
severity 417132 important
severity 417133 important
severity 417135 important
severity 417137 important
severity 417143 important
severity 417147 important
severity 417152 important
severity 417153 important
severity 417154 important
severity 417156 important
severity 417158 important
severity 417159 important
severity 417161 important
severity 417169 important
severity 417170 important
severity 417171 important
severity 417173 important
severity 417179 important
severity 417181 important
severity 417182 important
severity 417183 important
severity 417185 important
severity 417187 important
severity 417188 important
severity 417192 important
severity 417193 important
severity 417195 important
severity 417197 important
severity 417199 important
severity 417201 important
severity 417203 important
severity 417206 important
severity 417211 important
severity 417212 important
severity 417213 important
severity 417216 important
severity 417220 important
severity 417221 important
severity 417222 important
severity 417223 important
severity 417224 important
severity 417225 important
severity 417229 important
severity 417232 important
severity 417233 important
severity 417235 important
severity 417236 important
severity 417266 important
severity 417267 important
severity 417268 important
severity 417284 important
severity 417287 important
severity 417289 important
severity 417294 important
severity 417296 important
severity 417302 important
severity 417303 important
severity 417305 important
severity 417308 important
severity 417315 important
severity 417319 important
severity 417320 important
severity 417321 important
severity 417322 important
severity 417332 important
severity 417335 important
severity 417336 important
severity 417342 important
severity 417351 important
severity 417353 important
severity 417357 important
severity 417361 important
severity 417363 important
severity 417364 important
severity 417366 important
severity 417367 important
severity 417368 important
severity 417369 important
severity 417370 important
severity 417373 important
severity 417375 important
severity 417376 important
severity 417378 important
severity 417382 important
severity 417425 important
severity 417429 important
severity 417430 important
severity 417433 important
severity 417435 important
severity 417436 important
severity 417437 important
severity 417442 important
severity 417445 important
severity 417446 important
severity 417449 important
severity 417452 important
severity 417454 important
severity 417455 important
severity 417456 important
severity 417457 important
severity 417459 important
severity 417463 important
severity 417465 important
severity 417472 important
severity 417475 important
severity 417477 important
severity 417478 important
severity 417480 important
severity 417483 important
severity 417484 important
severity 417485 important
severity 417492 important
severity 417499 important
severity 417501 important
severity 417502 important
severity 417503 important
severity 417508 important
severity 417510 important
severity 417515 important
severity 417517 important
severity 417518 important
severity 417519 important
severity 417520 important
severity 417522 important
severity 417677 important
severity 417678 important
severity 417679 important
severity 417681 important
severity 417683 important
severity 417685 important
severity 417687 important
severity 417688 important
severity 417690 important
severity 417691 important
severity 417696 important
severity 417698 important
severity 417699 important
severity 417702 important
severity 417703 important
severity 417704 important
severity 417705 important
severity 417706 important
severity 417707 important
severity 417709 important
severity 417711 important
severity 417712 important
severity 417713 important
severity 417715 important
severity 417719 important
severity 417723 important
severity 417725 important
severity 417730 important
severity 417733 important
severity 417734 important
severity 417735 important
severity 417736 important
severity 417737 important
severity 417740 important
severity 417742 important
severity 417748 important
severity 417754 important
severity 417755 important
severity 417756 important
severity 417758 important
severity 417760 important
severity 417761 important
severity 417764 important
severity 417765 important
severity 417766 important
severity 417770 important
severity 417771 important
severity 417773 important
severity 417774 important
severity 417777 important
severity 417779 important
severity 417780 important
severity 417781 important
severity 417791 important
severity 417794 important
severity 417873 important
severity 417897 important
severity 418620 important
severity 419269 important
severity 419277 important
severity 419321 important
severity 420881 important
severity 420911 important
severity 420918 important
severity 420920 important
severity 420922 important
severity 421056 important
severity 421112 important
severity 421117 important
severity 421124 important
severity 421127 important
severity 421136 important
severity 421207 important
severity 421209 important
severity 421211 important
severity 421285 important
severity 422220 important
severity 425544 important
severity 425545 important
severity 413488 important
severity 415279 important
severity 417061 important
severity 417427 important
severity 417451 important
severity 417494 important
severity 417498 important
severity 417512 important
severity 421149 important
severity 417486 important
severity 413483 important
severity 416863 important
severity 417205 important
severity 417207 important
severity 417209 important
severity 417228 important
severity 417300 important
severity 417371 important
severity 417374 important
severity 417488 important
severity 417489 important
severity 417505 important
severity 417675 important
severity 417786 important
severity 421327 important
severity 417063 important
severity 417163 important
severity 417316 important
severity 417359 important
severity 417431 important
severity 417491 important
severity 417720 important
severity 417750 important
severity 417767 important
severity 417778 important
severity 420896 important
severity 420919 important
severity 421128 important
severity 421131 important
severity 417184 important
thanks

**Comment by epakai** [comment]
BTS_msg_id: <20080316220738.GA12627@olympe.madism.org>
BTS author: Pierre Habouzit <madcoder@debian.org>

--+QahgC5+KEYLbs62
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline

Hi,

Attached is the diff for my synergy 1.3.1-2.1 NMU.

--+QahgC5+KEYLbs62
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline; filename="synergy-1.3.1-2.1-nmu.diff"

diff -u synergy-1.3.1/debian/changelog synergy-1.3.1/debian/changelog
--- synergy-1.3.1/debian/changelog
+++ synergy-1.3.1/debian/changelog
@@ -1,3 +1,10 @@
+synergy (1.3.1-2.1) unstable; urgency=low
+
+  * Non-maintainer upload.
+  * fix g++-4.3 FTBFS (Closes: 417719).
+
+ -- Pierre Habouzit <madcoder@debian.org>  Sun, 16 Mar 2008 22:01:24 +0000
+
 synergy (1.3.1-2) unstable; urgency=low
 
   * added build-dependency on libxt-dev (closes: #367837)
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/arch/CArchDaemonUnix.cpp
+++ synergy-1.3.1/lib/arch/CArchDaemonUnix.cpp
@@ -18,6 +18,7 @@
 #include <sys/types.h>
 #include <sys/stat.h>
 #include <fcntl.h>
+#include <cstdlib>
 #include <errno.h>
 
 //
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/arch/CMultibyte.cpp
+++ synergy-1.3.1/lib/arch/CMultibyte.cpp
@@ -17,6 +17,7 @@
 
 #include "common.h"
 #include "CArch.h"
+#include <cstdlib>
 #include <limits.h>
 #include <string.h>
 #if HAVE_LOCALE_H
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/base/CStringUtil.cpp
+++ synergy-1.3.1/lib/base/CStringUtil.cpp
@@ -19,6 +19,7 @@
 #include <cctype>
 #include <cstdio>
 #include <cstdlib>
+#include <cstring>
 #include <algorithm>
 
 //
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/client/CServerProxy.cpp
+++ synergy-1.3.1/lib/client/CServerProxy.cpp
@@ -24,6 +24,7 @@
 #include "TMethodEventJob.h"
 #include "XBase.h"
 #include <memory>
+#include <cstring>
 
 //
 // CServerProxy
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/client/CClient.cpp
+++ synergy-1.3.1/lib/client/CClient.cpp
@@ -26,6 +26,8 @@
 #include "CLog.h"
 #include "IEventQueue.h"
 #include "TMethodEventJob.h"
+#include <cstdlib>
+#include <cstring>
 
 //
 // CClient
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/net/CTCPSocket.cpp
+++ synergy-1.3.1/lib/net/CTCPSocket.cpp
@@ -23,6 +23,7 @@
 #include "IEventJob.h"
 #include "CArch.h"
 #include "XArch.h"
+#include <cstdlib>
 #include <string.h>
 
 //
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/platform/CXWindowsScreen.cpp
+++ synergy-1.3.1/lib/platform/CXWindowsScreen.cpp
@@ -51,6 +51,7 @@
 #	endif
 #endif
 #include "CArch.h"
+#include <cstdlib>
 
 
 //
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/server/CClientProxy1_3.cpp
+++ synergy-1.3.1/lib/server/CClientProxy1_3.cpp
@@ -17,6 +17,7 @@
 #include "CLog.h"
 #include "IEventQueue.h"
 #include "TMethodEventJob.h"
+#include <cstring>
 
 //
 // CClientProxy1_3
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/server/CServer.cpp
+++ synergy-1.3.1/lib/server/CServer.cpp
@@ -29,6 +29,7 @@
 #include "TMethodEventJob.h"
 #include "CArch.h"
 #include <string.h>
+#include <cstdlib>
 
 //
 // CServer
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/synergy/CPacketStreamFilter.cpp
+++ synergy-1.3.1/lib/synergy/CPacketStreamFilter.cpp
@@ -16,6 +16,7 @@
 #include "IEventQueue.h"
 #include "CLock.h"
 #include "TMethodEventJob.h"
+#include <cstring>
 
 //
 // CPacketStreamFilter
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/synergy/IKeyState.cpp
+++ synergy-1.3.1/lib/synergy/IKeyState.cpp
@@ -13,6 +13,7 @@
  */
 
 #include "IKeyState.h"
+#include <cstdlib>
 #include <string.h>
 
 //
only in patch2:
unchanged:
--- synergy-1.3.1.orig/lib/synergy/IPrimaryScreen.cpp
+++ synergy-1.3.1/lib/synergy/IPrimaryScreen.cpp
@@ -13,6 +13,7 @@
  */
 
 #include "IPrimaryScreen.h"
+#include <cstdlib>
 
 //
 // IPrimaryScreen

--+QahgC5+KEYLbs62--

**Comment by epakai** [comment]
BTS_msg_id: <E1Jb1AC-0006P4-5E@ries.debian.org>
BTS author: Pierre Habouzit <madcoder@debian.org>

Source: synergy
Source-Version: 1.3.1-2.1

We believe that the bug you reported is fixed in the latest version of
synergy, which is due to be installed in the Debian FTP archive:

synergy_1.3.1-2.1.diff.gz
  to pool/main/s/synergy/synergy_1.3.1-2.1.diff.gz
synergy_1.3.1-2.1.dsc
  to pool/main/s/synergy/synergy_1.3.1-2.1.dsc
synergy_1.3.1-2.1_amd64.deb
  to pool/main/s/synergy/synergy_1.3.1-2.1_amd64.deb



A summary of the changes between this version and the previous one is
attached.

Thank you for reporting the bug, which will now be closed.  If you
have further comments please address them to 417719@bugs.debian.org,
and the maintainer will reopen the bug report if appropriate.

Debian distribution maintenance software
pp.
Pierre Habouzit <madcoder@debian.org> (supplier of updated synergy package)

(This message was generated automatically at their request; if you
believe that there is a problem with it please contact the archive
administrators by mailing ftpmaster@debian.org)


-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Format: 1.7
Date: Sun, 16 Mar 2008 22:01:24 +0000
Source: synergy
Binary: synergy
Architecture: source amd64
Version: 1.3.1-2.1
Distribution: unstable
Urgency: low
Maintainer: Cord Beermann <cord@debian.org>
Changed-By: Pierre Habouzit <madcoder@debian.org>
Description: 
 synergy    - Share mouse, keyboard and clipboard over the network
Closes: 417719
Changes: 
 synergy (1.3.1-2.1) unstable; urgency=low
 .
   * Non-maintainer upload.
   * fix g++-4.3 FTBFS (Closes: 417719).
Files: 
 a13e011f975bfd255c1a0c7a6aaab06f 636 x11 optional synergy_1.3.1-2.1.dsc
 c7eb49acd7d35ba9d590ffa38df0d758 32810 x11 optional synergy_1.3.1-2.1.diff.gz
 10f80bed60d21cf90492e31ad9f10871 638622 x11 optional synergy_1.3.1-2.1_amd64.deb

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.6 (GNU/Linux)

iD8DBQFH3ZrVvGr7W6HudhwRAu1fAJ9DmcSohSgYwX4PobRH2Y3HRYTvOwCeN+Bp
wpJjGdlBnxJ8nFljgkVBnPo=
=Shhc
-----END PGP SIGNATURE-----

**Comment by epakai** [comment]
BTS_msg_id: Bug archived.
BTS author: $requester

# A New Hope
# A log time ago, in a galaxy far, far away
# something happened.
#
# Magically this resulted in the following
# action being taken, but this fake control
# message doesn't tell you why it happened
#
# The action:
# Bug archived.
thanks
# This fakemail brought to you by your local debbugs
# administrator
